### ISSUE TITLE
Error after successful setup

### ISSUE THREAD

**Issue by Codepadawan** [dsifford/slack-polls#1]
Hi. I setup a node.js implementation on heroku, forked and installed this and the MongoLab add-on, and the setup command worked. I got 

```
Webhook URL successfully stored in the database. You're all set!
```

I then did a /poll new command, and whilst this correctly generated a record in the DB, I got back an error:

```
<DOCTYPE html>
   <html>
   <head>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <style type="text/css">
       html, body, iframe { margin: 0; padding: 0; height: 100%; }
       iframe { display: block; width: 100%; border: none; }
     </style>
   <title>Application Error</title>
   </head>
   <body>
     <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
       <p>Application Error</p>
     </iframe>
   </body>
   </html>
```

All subsequent commands returned an error - and voting doesn't appear to work either. I've no familiarity with node.js (though with other languages and javascript in general) so not sure what to do next.

**Comment by Codepadawan** [comment]
I deleted the mongolab add-on and re-ran /poll setup. Following this, /poll help worked... once... and afterwards I just got errors. So it appears that the first command run after setup works, then nothing else works.

**Comment by Codepadawan** [comment]
Restarted my dyno. Now seems to be working.

**Comment by dsifford** [comment]
Glad you were able to get this working @Codepadawan. Let me know if you run into anymore issues. Admittedly, I've let this repo get a bit dusty and haven't really dug into the code in quite some time.
